# Generated by Django 2.2.6 on 2019-10-24 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название станка')),
            ],
            options={
                'verbose_name': 'Станок',
                'verbose_name_plural': 'Станки',
            },
        ),
        migrations.CreateModel(
            name='ProductionEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип производственного оборудования')),
            ],
            options={
                'verbose_name': 'Тип производственного оборудования',
                'verbose_name_plural': 'Типы производственного оборудования',
            },
        ),
        migrations.CreateModel(
            name='ProductionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.FloatField(verbose_name='Производственная площадь')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sprav.Machine', verbose_name='Станок')),
            ],
            options={
                'verbose_name': 'Производственная площадь',
                'verbose_name_plural': 'Производственная площади',
            },
        ),
        migrations.CreateModel(
            name='MachinesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип станка')),
                ('equip_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sprav.ProductionEquipment', verbose_name='Тип производственного оборудования')),
            ],
            options={
                'verbose_name': 'Тип станка',
                'verbose_name_plural': 'Типы станков',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sprav.MachinesType', verbose_name='Тип станка'),
        ),
    ]
